import assert from 'node:assert/strict';
import {Input,BufferSource,ALL_FORMATS} from 'mediabunny';
import fs from 'node:fs/promises';
import path from 'node:path';
import {createRequire} from 'node:module';
const require=createRequire(import.meta.url);
const {chromium}=require(path.join(process.env.USERPROFILE,'.cache/codex-runtimes/codex-primary-runtime/dependencies/node/node_modules/playwright'));
const out=path.resolve('test-results');await fs.mkdir(out,{recursive:true});
const browser=await chromium.launch({channel:'chrome',headless:true,args:['--autoplay-policy=no-user-gesture-required']});
const page=await browser.newPage({viewport:{width:1440,height:1000},acceptDownloads:true});
const errors=[];page.on('pageerror',e=>errors.push(e.message));page.on('dialog',d=>d.accept());
const chart={version:1,meta:{title:'渲染测试',bpm:120,offsetSeconds:0,ppq:480,timeSignature:{numerator:4,denominator:4},seed:123,music:null},notes:[{id:'a',tick:960,height:.2},{id:'b',tick:1080,height:.8},{id:'c',tick:2400,height:.3},{id:'d',tick:3360,height:.6}]};
async function upload(selector,obj){await page.locator(selector).setInputFiles({name:'test.json',mimeType:'application/json',buffer:Buffer.from(JSON.stringify(obj))});}
async function download(selector){const event=page.waitForEvent('download');await page.locator(selector).click();const d=await event;return JSON.parse(await fs.readFile(await d.path(),'utf8'));}
async function seek(time){await page.locator('#seek').evaluate((el,t)=>{el.value=t;el.dispatchEvent(new Event('input',{bubbles:true}));},time);}
async function field(name,value){const el=page.getByLabel(name,{exact:true});await el.fill(String(value));await el.press('Tab');}
try{
 await page.goto(process.env.RENDERER_URL||'http://127.0.0.1:5175');await page.locator('#materials').click();await page.frameLocator('#editor').locator('#slots').waitFor();await page.locator('#preset').click();await page.waitForFunction(()=>document.querySelector('#status').textContent.startsWith('项目素材已载入'),{},{timeout:60000});
 const frame=page.frameLocator('#editor');assert.equal(await frame.locator('.slot small').allTextContents().then(a=>a.join(',')),'4 帧,5 帧,5 帧,5 帧,3 帧,6 张');
 await frame.locator('[data-slot="0"]').click();await frame.getByLabel('缩放',{exact:true}).fill('.9');await frame.getByLabel('缩放',{exact:true}).press('Tab');await frame.locator('#fps').fill('12');await frame.locator('#fps').press('Tab');await frame.locator('#apply').click();await page.locator('#closeAssets').click();
 await upload('#chartFile',chart);await page.waitForFunction(()=>document.querySelector('#status').textContent.startsWith('已载入 4'));
 const musicDir=path.resolve('../../src/Music');const music=(await fs.readdir(musicDir)).find(n=>n.endsWith('.flac'));await page.locator('#musicFile').setInputFiles(path.join(musicDir,music));await page.waitForFunction(()=>document.querySelector('#status').textContent.startsWith('已载入音乐'),{},{timeout:60000});
 await field('片段结束（秒）',4);await seek(1.8);await page.locator('#play').click();await page.waitForFunction(()=>parseFloat(document.querySelector('#time').textContent)>2.1,{},{timeout:5000});await page.locator('#play').click();assert.ok(parseFloat(await page.locator('#time').textContent())>2.1);
 await seek(2.49);await page.screenshot({path:path.join(out,'renderer-hit.png')});const first=await page.locator('#canvas').evaluate(c=>c.toDataURL());await seek(.1);await seek(2.49);assert.equal(await page.locator('#canvas').evaluate(c=>c.toDataURL()),first);
 await page.locator('#mode').selectOption('miss');await seek(2.8);await page.screenshot({path:path.join(out,'renderer-miss.png')});assert.notEqual(await page.locator('#canvas').evaluate(c=>c.toDataURL()),first);
 await page.locator('#random').click();const changed=await download('#exportChart');assert.notEqual(changed.meta.seed,123);assert.deepEqual(changed.notes,chart.notes);
 await field('活动区域高度（%）',30);await field('活动区域中心（%）',50);await field('人物全局缩放（%）',120);await field('怪物全局缩放（%）',80);await field('特效全局缩放（%）',90);await field('入场时长（秒）',1.2);await field('入场提前量（秒）',.4);await page.locator('#exitEnabled').check();await field('退场时长（秒）',.7);
 const cfg=await download('#save');assert.equal(cfg.settings.top,.35);assert.equal(cfg.settings.bottom,.65);assert.equal(cfg.settings.characterScale,1.2);assert.equal(cfg.settings.monsterScale,.8);assert.equal(cfg.settings.fxScale,.9);assert.equal(cfg.settings.entranceDuration,1.2);assert.equal(cfg.settings.exitEnabled,true);assert.equal(cfg.assets.slots[0].transforms[0].scale,.9);assert.equal(cfg.settings.mode,'miss');
 await upload('#configFile',{version:1,settings:{...cfg.settings,moveDuration:0},assets:cfg.assets});await page.waitForFunction(()=>document.querySelector('#status').textContent.startsWith('配置未载入'));assert.equal((await download('#save')).settings.moveDuration,cfg.settings.moveDuration);

 await page.locator('#dimensionMode').selectOption('locked');await page.locator('#ratio').selectOption('1');await page.locator('#outWidth').fill('160');await page.locator('#outWidth').press('Tab');assert.equal(await page.locator('#outHeight').inputValue(),'160');
 await page.locator('#dimensionMode').selectOption('free');await page.locator('#outHeight').fill('90');await page.locator('#outHeight').press('Tab');await page.locator('#exportMode').selectOption('stepped');assert.equal(await page.locator('#outputFps').isVisible(),false);await page.locator('#stepFps').fill('10');await page.locator('#stepFps').press('Tab');await page.locator('#saveMethod').selectOption('zip');
 await page.locator('#showCharacter').uncheck();await page.locator('#showMonsters').uncheck();await page.locator('#showFx').uncheck();await page.locator('summary').filter({hasText:/^怪物$/}).click();await page.locator('#monsterFloat').check();
 const exportEvent=page.waitForEvent('download',{timeout:60000});await page.locator('#exportFrames').click();const zipped=await exportEvent;const zipBytes=await fs.readFile(await zipped.path());const entries=new Map();let z=0;while(zipBytes.readUInt32LE(z)===0x04034b50){const size=zipBytes.readUInt32LE(z+18),nl=zipBytes.readUInt16LE(z+26),xl=zipBytes.readUInt16LE(z+28),name=zipBytes.subarray(z+30,z+30+nl).toString();entries.set(name,zipBytes.subarray(z+30+nl+xl,z+30+nl+xl+size));z+=30+nl+xl+size;}const timeline=JSON.parse(entries.get('timeline.json'));assert.equal(timeline.fps,10);assert.equal(timeline.spriteFps,12);assert.equal(timeline.width,160);assert.equal(timeline.height,90);const png=entries.get('frame_0000000.png');assert.equal(png.readUInt32BE(16),160);assert.equal(png.readUInt32BE(20),90);assert.equal(entries.size,timeline.frameCount+1);await page.waitForFunction(()=>!document.querySelector('#exportDialog').open);

 await page.locator('#showCharacter').check();await page.locator('#showMonsters').check();await page.locator('#showFx').check();
 await seek(timeline.firstFrameTime+1.01);const held=await page.locator('#canvas').evaluate(c=>c.toDataURL());await seek(timeline.firstFrameTime+1.04);assert.equal(await page.locator('#canvas').evaluate(c=>c.toDataURL()),held);assert.equal(await page.locator('#stepFps').inputValue(),'10');
 for(const mode of ['normal','stepped']){
  await page.locator('#exportMode').selectOption(mode);if(mode==='normal'){await page.locator('#outputFps').fill('24');await page.locator('#outputFps').press('Tab');}else{assert.equal(await page.locator('#stepFps').inputValue(),'10');assert.equal(await page.locator('#outputFps').isVisible(),false);}await page.locator('#saveMethod').selectOption('mp4');
  const mp4Event=page.waitForEvent('download',{timeout:60000});await page.locator('#exportFrames').click();const mp4=await Promise.race([mp4Event,page.waitForFunction(()=>document.querySelector('#status').textContent.startsWith('导出失败'),{},{timeout:60000}).then(async()=>{throw Error(await page.locator('#status').textContent());})]);const bytes=await fs.readFile(await mp4.path());await fs.writeFile(path.join(out,mode+'.mp4'),bytes);const input=new Input({source:new BufferSource(bytes),formats:ALL_FORMATS});const vt=await input.getPrimaryVideoTrack(),at=await input.getPrimaryAudioTrack();assert.equal(vt.displayWidth,160);assert.equal(vt.displayHeight,90);assert.ok(at);const stats=await vt.computePacketStats();assert.ok(Math.abs(stats.averagePacketRate-(mode==='normal'?24:10))<.01);assert.ok(Math.abs(await vt.computeDuration()-await at.computeDuration())<.15);input.dispose();await page.evaluate(async base64=>{const data=Uint8Array.from(atob(base64),c=>c.charCodeAt(0));const url=URL.createObjectURL(new Blob([data],{type:'video/mp4'}));const video=document.createElement('video');video.muted=true;video.src=url;await new Promise((resolve,reject)=>{video.onloadeddata=resolve;video.onerror=()=>reject(Error('MP4 解码失败'));});video.currentTime=video.duration/2;await new Promise(resolve=>video.onseeked=resolve);if(video.videoWidth!==160||video.readyState<2)throw Error('视频解码未完成');URL.revokeObjectURL(url);video.remove();},bytes.toString('base64'));await page.waitForFunction(()=>!document.querySelector('#exportDialog').open);
 }
 await page.locator('#stepFps').scrollIntoViewIfNeeded();await page.screenshot({path:path.join(out,'renderer-output.png')});
 await upload('#configFile',cfg);await page.waitForFunction(()=>document.querySelector('#status').textContent.startsWith('配置已载入'));
 await page.locator('summary').filter({hasText:/^打击特效$/}).click();assert.equal(await page.getByLabel('淡出时长（秒）',{exact:true}).isDisabled(),true);await page.locator('#fxFade').check();await field('淡出时长（秒）',.5);await field('淡出延后（秒）',.1);await page.locator('#mode').selectOption('hit');
 const fadeCfg=await download('#save');assert.equal(fadeCfg.settings.fxFade,true);assert.equal(fadeCfg.settings.fxFadeDuration,.5);assert.equal(fadeCfg.settings.fxFadeDelay,.1);
 await page.evaluate(()=>{const ctx=document.querySelector('#canvas').getContext('2d');const original=ctx.drawImage.bind(ctx);ctx.drawImage=function(img,...args){const frames=document.querySelector('#editor').contentWindow.animationImporter.applied.frames[4];if(frames.some(f=>f.image===img))window.lastFxAlpha=this.globalAlpha;return original(img,...args);};});
 await seek(3.8);assert.ok(Math.abs(await page.evaluate(()=>window.lastFxAlpha)-.6)<.005);await page.locator('#fxHoldLast').uncheck();await page.evaluate(()=>window.lastFxAlpha=null);await seek(3.8);assert.equal(await page.evaluate(()=>window.lastFxAlpha),null);assert.equal((await download('#save')).settings.fxHoldLast,false);
 await upload('#configFile',cfg);await page.waitForFunction(()=>document.querySelector('#status').textContent.startsWith('配置已载入'));assert.equal(await page.locator('#fxFade').isChecked(),false);
 const dup=structuredClone(chart);dup.notes.push({...dup.notes[0],id:'same-time'});await upload('#chartFile',dup);await page.waitForFunction(()=>document.querySelector('#status').textContent.startsWith('已载入 5'));await page.locator('#mode').selectOption('hit');await page.locator('#play').click();await page.waitForFunction(()=>document.querySelector('#status').textContent.includes('同刻多音符'));await page.locator('#mode').selectOption('miss');await page.locator('#play').click();assert.equal(await page.locator('#play').textContent(),'暂停');await page.locator('#play').click();
 await upload('#chartFile',chart);await page.waitForFunction(()=>document.querySelector('#status').textContent.startsWith('已载入 4'));await page.locator('#record').click();assert.equal(await page.evaluate(()=>document.fullscreenElement?.id),'screen');await page.waitForFunction(()=>document.querySelector('#play').textContent==='暂停');assert.equal(await page.locator('#count').textContent(),'');await page.evaluate(()=>document.exitFullscreen());await page.waitForFunction(()=>document.querySelector('#play').textContent==='播放');
 await seek(3.8);await page.locator('#play').click();await page.waitForFunction(()=>document.querySelector('#status').textContent==='片段播放结束',{},{timeout:15000});const ended=await page.locator('#time').textContent();await page.waitForTimeout(150);assert.equal(await page.locator('#time').textContent(),ended);
 await page.reload();await page.frameLocator('#editor').locator('#slots').waitFor({state:'attached'});await upload('#configFile',cfg);await page.waitForFunction(()=>document.querySelector('#status').textContent.startsWith('配置已载入'));assert.equal((await download('#save')).assets.slots[0].transforms[0].scale,.9);
 await page.locator('#materials').click();const idlePath=path.resolve('../../src/EquidistantWhiteEdgeStopMotionMovie/Idle');await frame.locator('#fileInput').setInputFiles([1,2,3,4].map(n=>path.join(idlePath,n+'.png')));await frame.locator('#apply').click();assert.equal((await page.evaluate(()=>document.querySelector('#editor').contentWindow.animationImporter.applied.config.slots[0].transforms[0].scale)),.9);await page.screenshot({path:path.join(out,'renderer-materials.png')});
 assert.deepEqual(errors,[]);console.log('PASS: embedded importer, real PNG/FLAC, seek determinism, both modes, seed export, invalid config, same-time rule, reload/relink');
}finally{await browser.close();}
