import {test} from 'node:test';
import assert from 'node:assert/strict';
import {defaults,compile,actorAt,monsterAt,hash,hitConflicts,validateSettings,transitionTimes,actorXAt,compositionRange,monsterDrift,sampledTime,logicalWidth,gridOrigin,effectAt,effectDuration} from '../src/engine.js';
import {freshChart,parseChart,serializeChart} from '../../chart-editor/src/core.ts';
const make=()=>({...freshChart(),notes:[{id:'a',tick:960,height:.2},{id:'b',tick:1056,height:.8},{id:'c',tick:2880,height:.5}]});
const counts=[4,5,5,5,3];
test('seed round trip through existing chart format and old charts',()=>{const c=make();c.meta.seed=4294967295;assert.equal(parseChart(serializeChart(c)).meta.seed,4294967295);delete c.meta.seed;assert.equal(parseChart(serializeChart(c)).meta.seed,1);assert.equal(hash(123,'a'),hash(123,'a'));assert.notEqual(hash(123,'a'),hash(123,'b'));});
test('dense movement interrupts from exact current position without accelerating',()=>{const p={...defaults,bobAmplitude:0,moveLead:.25,moveDuration:.4};const e=compile(make(),p,counts,8);const at=actorAt(e,e[1].move-1e-8,p,counts,8);assert.ok(Math.abs(at.height-e[1].from)<1e-6);assert.ok(Math.abs(actorAt(e,e[1].move+.2,p,counts,8).height-(e[1].from+(.8-e[1].from)*.875))<1e-8);});
test('dense attacks restart at frame zero without changing fps',()=>{const p={...defaults};const e=compile(make(),p,counts,8);assert.equal(actorAt(e,e[1].attack+.001,p,counts,8).frame,0);assert.equal(actorAt(e,e[1].attack+.13,p,counts,8).frame,1);});
test('time seeking is deterministic and miss stays centered',()=>{const p={...defaults};const e=compile(make(),p,counts,8);const direct=actorAt(e,2.4,p,counts,8);for(let t=0;t<3;t+=.016)actorAt(e,t,p,counts,8);assert.deepEqual(actorAt(e,2.4,p,counts,8),direct);const miss=actorAt(e,2.4,{...p,mode:'miss'},counts,8);assert.equal(miss.slot,0);assert.ok(Math.abs(miss.height-.5)<=p.bobAmplitude);});
test('hit line timing and miss left boundary use entire sprite radius',()=>{const e=compile(make(),defaults,counts,8)[0];assert.equal(monsterAt(e,e.time,defaults,120,100).visible,false);const miss={...defaults,mode:'miss'};assert.equal(monsterAt(e,e.time,miss,120,100).x,defaults.hitX*1920);assert.equal(monsterAt(e,e.time+.1,miss,120,100).visible,true);assert.equal(monsterAt(e,e.time+10,miss,120,100).visible,false);});
test('same-time detection and invalid settings',()=>{const c=make();c.notes.push({...c.notes[0],id:'another'});assert.equal(hitConflicts(compile(c,defaults,counts,8)),true);assert.throws(()=>validateSettings({...defaults,moveDuration:0}));assert.throws(()=>validateSettings({...defaults,top:.9,bottom:.2}));});

test('composition percent conversion preserves normalized range',()=>{assert.deepEqual(compositionRange(50,30),{top:.35,bottom:.65});assert.equal(validateSettings({...defaults,...compositionRange(45,40)}).bottom,.65);});
test('entry completes before first clip note with cubic easeOut',()=>{const p={...defaults,entranceDuration:2,entranceLead:.5};const e=compile(make(),p,counts,8),timing=transitionTimes(e,p,counts,8);assert.equal(timing.enterEnd,.5);assert.equal(timing.enterStart,-1.5);assert.equal(actorXAt(-2,p,timing,100),-101);assert.equal(actorXAt(.5,p,timing,100),p.characterX*1920);assert.ok(Math.abs(actorXAt(-.5,p,timing,100)-(-101+(p.characterX*1920+101)*.875))<1e-9);});
test('optional exit waits for actions and fx, then fully leaves left edge',()=>{const p={...defaults,exitEnabled:true,exitDuration:1};const e=compile(make(),p,counts,8),timing=transitionTimes(e,p,counts,8);assert.ok(timing.leaveStart>=e.at(-1).attackEnd);assert.ok(timing.leaveStart>=e.at(-1).time+counts[4]/8);assert.equal(actorXAt(timing.leaveEnd,p,timing,200),-201);assert.equal(actorXAt(timing.leaveEnd,{...p,exitEnabled:false},timing,200),p.characterX*1920);});
test('clip start picks its first note and settings accept legacy config',()=>{const p={...defaults,start:2};const e=compile(make(),p,counts,8);assert.equal(transitionTimes(e,p,counts,8).enterEnd,3-p.entranceLead);const old={...defaults};delete old.entranceDuration;delete old.exitEnabled;assert.equal(validateSettings(old).exitEnabled,false);assert.throws(()=>validateSettings({...defaults,exitDuration:0}));});

test('monster size does not change position or velocity',()=>{const e=compile(make(),defaults,counts,8)[0];assert.equal(monsterAt(e,0,defaults,120,20).x,monsterAt(e,0,defaults,120,400).x);assert.equal(monsterAt(e,.2,defaults,120,20).x-monsterAt(e,.1,defaults,120,20).x,monsterAt(e,.2,defaults,120,400).x-monsterAt(e,.1,defaults,120,400).x);});
test('drift is seeded per note and converges exactly at hit',()=>{const p={...defaults,monsterFloat:true};const e=compile(make(),p,counts,12);assert.equal(monsterDrift(e[0],e[0].time,p,42,120),0);assert.notEqual(monsterDrift(e[0],0,p,42,120),monsterDrift(e[1],0,p,42,120));assert.equal(monsterDrift(e[0],0,p,42,120),monsterDrift(e[0],0,p,42,120));assert.notEqual(monsterDrift(e[0],e[0].time,{...p,mode:'miss'},42,120),0);});
test('global sampling holds all motion on shared frame lattice',()=>{const p={...defaults,exportMode:'stepped',stepFps:10};const origin=-.125;assert.equal(sampledTime(origin+.01,p,origin),sampledTime(origin+.07,p,origin));assert.ok(Math.abs(sampledTime(origin+1/10,p,origin)-(origin+1/10))<1e-9);assert.equal(sampledTime(.031,defaults,origin),.031);const e=compile(make(),p,counts,12),o=gridOrigin(make(),p);assert.ok(Math.abs((e[0].attack-o)*10-Math.round((e[0].attack-o)*10))<1e-8);});
test('resolution changes preserve height-relative composition',()=>{assert.equal(logicalWidth({...defaults,outputWidth:3840,outputHeight:2160}),1920);assert.equal(logicalWidth({...defaults,outputWidth:1080,outputHeight:1080}),1080);assert.throws(()=>validateSettings({...defaults,outputWidth:1}));assert.throws(()=>validateSettings({...defaults,outputHeight:1080.5}));});

test('sampling FPS is independent of animation duration and validated',()=>{const p={...defaults,exportMode:'stepped',stepFps:7};const e=compile(make(),p,counts,12);assert.ok(Math.abs(e[0].attackEnd-e[0].attack-counts[e[0].action]/12)<1e-9);assert.equal(validateSettings({...p,stepFps:25}).stepFps,25);for(const stepFps of [0,121,NaN])assert.throws(()=>validateSettings({...p,stepFps}));});

test('effect fade delays, fades linearly and holds final frame until completion',()=>{const p={...defaults,fxFade:true,fxFadeDelay:.5,fxFadeDuration:1};assert.deepEqual(effectAt(.4,p,3,12),{frame:2,alpha:1});assert.deepEqual(effectAt(1,p,3,12),{frame:2,alpha:.5});assert.equal(effectAt(1.5,p,3,12),null);assert.equal(effectAt(-.1,p,3,12),null);assert.equal(effectDuration(defaults,3,12),.25);assert.equal(effectAt(.25,defaults,3,12),null);const early={...p,fxFadeDelay:0,fxFadeDuration:.1};assert.equal(effectAt(.1,early,3,12),null);const e=compile(make(),p,counts,12),t=transitionTimes(e,p,counts,12);assert.ok(t.leaveStart>=e.at(-1).time+1.5);assert.equal(validateSettings({}).fxFade,false);assert.throws(()=>validateSettings({...p,fxFadeDuration:0}));assert.throws(()=>validateSettings({...p,fxFadeDelay:-1}));assert.throws(()=>validateSettings({...p,fxFade:'yes'}));});

test('effect can end with source frames without holding, including exit timing',()=>{const p={...defaults,fxFade:true,fxHoldLast:false,fxFadeDelay:.5,fxFadeDuration:1};assert.equal(effectDuration(p,3,12),.25);assert.equal(effectAt(.25,p,3,12),null);assert.deepEqual(effectAt(.2,p,3,12),{frame:2,alpha:1});assert.equal(effectDuration({...p,fxFadeDelay:0,fxFadeDuration:.1},3,12),.1);const e=compile(make(),p,counts,12);assert.equal(transitionTimes(e,p,counts,12).leaveStart,transitionTimes(e,{...p,fxFade:false},counts,12).leaveStart);});
