export const WIDTH=1920,HEIGHT=1080;
export const defaults={mode:'hit',characterX:.22,hitX:.32,top:.2,bottom:.8,characterScale:.7,monsterScale:.6,fxScale:.7,travelBeats:4,moveLead:.25,moveDuration:.18,attackOffset:-.125,flatThreshold:.025,bobAmplitude:.012,bobPeriod:3,hitDx:130,hitDy:0,background:'#dedfe9',countdown:3,tail:1,start:0,end:0,debug:false,enabledMonsters:[]};
export const limits={characterX:[0,1],hitX:[.05,.95],top:[0,1],bottom:[0,1],characterScale:[.05,3],monsterScale:[.05,3],fxScale:[.05,3],travelBeats:[.1,32],moveLead:[0,5],moveDuration:[.01,5],attackOffset:[-5,5],flatThreshold:[0,1],bobAmplitude:[0,.2],bobPeriod:[.1,30],hitDx:[-1920,1920],hitDy:[-1080,1080],countdown:[0,10],tail:[0,20],start:[0,86400],end:[0,86400]};
export function validateSettings(value){if(!value||typeof value!=='object')throw Error('渲染参数无效');const p={...defaults,...value};for(const [k,[min,max]]of Object.entries(limits))if(typeof p[k]!=='number'||!Number.isFinite(p[k])||p[k]<min||p[k]>max)throw Error(`参数 ${k} 超出范围`);if(!['hit','miss'].includes(p.mode)||p.top>=p.bottom||!/^#[0-9a-f]{6}$/i.test(p.background)||typeof p.debug!=='boolean'||!Array.isArray(p.enabledMonsters)||!p.enabledMonsters.every(n=>typeof n==='string'))throw Error('渲染配置无效');if(p.end&&p.end<=p.start)throw Error('片段结束必须晚于开始');return p;}
export const clamp=(v,a,b)=>Math.max(a,Math.min(b,v));
export const ease=v=>1-(1-clamp(v,0,1))**3;
export const noteTime=(n,m)=>m.offsetSeconds+n.tick*60/(m.bpm*m.ppq);
export function hash(seed,id){let h=(2166136261^(seed>>>0))>>>0;for(let i=0;i<id.length;i++){h^=id.charCodeAt(i);h=Math.imul(h,16777619);}h^=h>>>16;return h>>>0;}
export function lastAt(list,t,key){let lo=0,hi=list.length;while(lo<hi){const mid=(lo+hi)>>>1;if(list[mid][key]<=t)lo=mid+1;else hi=mid;}return lo-1;}
function bob(t,p){return p.bobAmplitude*Math.sin(2*Math.PI*t/p.bobPeriod);}
function moveY(e,t,p){if(!e)return .5+bob(t,p);const end=e.move+p.moveDuration;if(t<end)return e.from+(e.height-e.from)*ease((t-e.move)/p.moveDuration);return e.height;}
function actorY(movement,attack,t,p){let y=moveY(movement,t,p);const moving=movement&&t<movement.move+p.moveDuration;const attacking=attack&&t<attack.attackEnd;if(!moving&&!attacking){const rest=Math.max(movement?movement.move+p.moveDuration:0,attack?attack.attackEnd:0);y=(movement?movement.height:.5)+bob(t-rest,p);}return y;}
export function compile(chart,p,counts=[4,5,5,5,3],fps=8){const notes=chart.notes.map(n=>({...n,time:noteTime(n,chart.meta)})).sort((a,b)=>a.time-b.time||a.id.localeCompare(b.id));const events=[];for(const n of notes){const move=n.time-p.moveLead;const previous=events.at(-1);const attackIndex=lastAt(events,move,'attack');const from=actorY(previous,events[attackIndex],move,p);const delta=n.height-from;const action=Math.abs(delta)<=p.flatThreshold?3:delta<0?1:2;const attack=n.time+p.attackOffset;events.push({...n,move,from,action,attack,attackEnd:attack+(counts[action]||1)/fps});}return events;}
export function actorAt(events,t,p,counts,fps){if(p.mode==='miss')return{height:.5+bob(t,p),slot:0,frame:((Math.floor(t*fps)%counts[0])+counts[0])%counts[0]};const movement=events[lastAt(events,t,'move')],attack=events[lastAt(events,t,'attack')];let slot=0,index=Math.floor(t*fps);if(attack&&t<attack.attackEnd){slot=attack.action;index=Math.floor((t-attack.attack)*fps);}return{height:actorY(movement,attack,t,p),slot,frame:((index%counts[slot])+counts[slot])%counts[slot]};}
export function monsterAt(event,t,p,bpm,radius=0){const travel=p.travelBeats*60/bpm,spawn=WIDTH+radius,speed=(spawn-p.hitX*WIDTH)/travel;const x=p.hitX*WIDTH+(event.time-t)*speed;return{x,visible:t>=event.time-travel&&(p.mode==='miss'?x+radius>=0:t<event.time)};}
export function hitConflicts(events){for(let i=1;i<events.length;i++)if(events[i].time===events[i-1].time)return true;return false;}
