import './style.css';
import {parseChart,serializeChart} from '../../chart-editor/src/core.ts';
import {parseConfig,defaults as assetDefaults,transformPoint} from '../../animation-importer/src/core.js';
import {WIDTH,HEIGHT,defaults,validateSettings,compile,actorAt,monsterAt,hash,lastAt,hitConflicts,limits} from './engine.js';
import {Clock} from './clock.js';
const $=s=>document.querySelector(s),clone=v=>structuredClone(v),clock=new Clock();
let chart=null,music=null,assets=null,p={...defaults},events=[],counts=[4,5,5,5,3],fps=8,loading=false,recording=false,unsaved=false,chartDirty=false;
const bundled=import.meta.glob('../../../src/EquidistantWhiteEdgeStopMotionMovie/*/*.png',{eager:true,query:'?url',import:'default'});
const groups=['Idle','Upper','Lower','Stright','Hitfx','Monsters'];
const fields=(list)=>list.map(([key,label,step])=>`<label class="field">${label}<input type="number" data-setting="${key}" aria-label="${label}" min="${limits[key][0]}" max="${limits[key][1]}" step="${step??.01}" value="${p[key]}"></label>`).join('');
$('#app').innerHTML=`<header><div class="inline"><h1>PV 渲染器</h1><span id="info"></span></div><nav><button id="chart">导入谱面</button><button id="music">导入音乐</button><button id="materials">素材</button><button id="open">打开配置</button><button id="save">保存配置</button></nav></header><main><section class="workspace"><div class="screen" id="screen"><canvas id="canvas" width="1920" height="1080" aria-label="PV 预览"></canvas><div id="count"></div></div><input id="seek" aria-label="播放位置" type="range" min="0" max="1" step="0.001" value="0"><div class="transport"><button class="primary" id="play">播放</button><button id="restart">从头播放</button><span id="time" class="time">0.000 s</span><button id="fullscreen">全屏</button><button id="record">录屏模式</button></div><div id="status" role="status">导入谱面、音乐，并在素材窗口加载图片</div></section><aside><h2>播放</h2><label class="field">模式<select id="mode"><option value="hit">全部击打</option><option value="miss">全部 Miss</option></select></label>${fields([['start','片段开始（秒）',.1],['end','片段结束（秒）',.1]])}<label class="field">Seed<input id="seed" type="number" min="0" max="4294967295" step="1" value="1"></label><div class="inline"><button id="random">重新随机</button><button id="exportChart">保存谱面</button></div><details open><summary>动作</summary>${fields([['moveLead','移动提前（秒）'],['moveDuration','缓动时长（秒）'],['attackOffset','攻击偏移（秒）'],['flatThreshold','平砍阈值']])}</details><details><summary>待机浮动</summary>${fields([['bobAmplitude','幅度'],['bobPeriod','周期（秒）',.1]])}</details><details><summary>画面</summary>${fields([['characterX','人物横向位置'],['hitX','打击线'],['top','高度上限'],['bottom','高度下限'],['characterScale','人物缩放'],['monsterScale','怪物缩放'],['fxScale','特效缩放'],['hitDx','命中偏移 X',1],['hitDy','命中偏移 Y',1]])}<label class="field">背景<input type="color" id="background" value="${p.background}"></label></details><details><summary>怪物</summary>${fields([['travelBeats','飞行提前（拍）',.25]])}<div id="monsters"></div></details><details><summary>录屏</summary>${fields([['countdown','倒计时（秒）',1],['tail','最少收尾（秒）',.1]])}</details><label class="field">调试叠层<input type="checkbox" id="debug"></label></aside></main><dialog id="assetDialog"><div class="modalbar"><strong>素材</strong><div><button id="preset">载入项目素材</button><button id="closeAssets">关闭</button></div></div><iframe id="editor" title="动画导入器" src="./editor.html"></iframe></dialog><input id="chartFile" type="file" accept=".json" hidden><input id="musicFile" type="file" accept="audio/*,.flac" hidden><input id="configFile" type="file" accept=".json" hidden>`;
const canvas=$('#canvas'),ctx=canvas.getContext('2d');
const bridge=()=>$('#editor').contentWindow.animationImporter;
function status(s,error=false){$('#status').textContent=s;$('#status').classList.toggle('error',error);}
function pause(){if(clock.playing)status('已暂停');clock.pause();$('#play').textContent='播放';$('#count').textContent='';}
function end(){return p.end||clock.buffer?.duration||0;}
function rebuild(){fps=assets?.config.fps||8;counts=assets?assets.frames.slice(0,5).map(a=>a.length||1):[4,5,5,5,3];events=chart?compile(chart,p,counts,fps).filter(n=>!clock.buffer||n.time<=end()):[];$('#seek').min=p.start;$('#seek').max=Math.max(p.start+.001,end());render();}
function syncUI(){for(const el of document.querySelectorAll('[data-setting]'))el.value=p[el.dataset.setting];$('#mode').value=p.mode;$('#background').value=p.background;$('#debug').checked=p.debug;$('#seed').value=chart?.meta.seed??1;$('#info').textContent=chart?.meta.title??'';monsterUI();}
function enabled(){return assets?assets.config.slots[5].files.map((name,index)=>({name,index})).filter(v=>p.enabledMonsters.includes(v.name)):[];}
function monsterUI(){const box=$('#monsters');box.replaceChildren();for(const name of assets?.config.slots[5].files??[]){const l=document.createElement('label');l.className='monster';const c=document.createElement('input');c.type='checkbox';c.checked=p.enabledMonsters.includes(name);c.onchange=()=>{pause();p.enabledMonsters=c.checked?[...p.enabledMonsters,name]:p.enabledMonsters.filter(n=>n!==name);unsaved=true;render();};l.append(c,document.createTextNode(name));box.append(l);}}
function acceptAssets(){const result=bridge().applied;if(!result)return;pause();assets=result;const available=assets.config.slots[5].files;p.enabledMonsters=p.enabledMonsters.filter(n=>available.includes(n));if(!p.enabledMonsters.length)p.enabledMonsters=[...available];unsaved=true;syncUI();rebuild();status('素材已应用');}
$('#editor').addEventListener('load',()=>{const win=$('#editor').contentWindow;win.addEventListener('animation-assets-applied',acceptAssets);});
function drawSprite(slot,index,x,y,scale){const f=assets?.frames[slot]?.[index],t=assets?.config.slots[slot].transforms[slot===5?index:0];if(!f||!t)return;ctx.save();ctx.translate(x,y);ctx.rotate(t.rotation*Math.PI/180);ctx.scale(scale*t.scale,scale*t.scale);ctx.translate(-t.anchor.x,-t.anchor.y);const c=t.crop;ctx.beginPath();ctx.rect(c.x,c.y,c.w,c.h);ctx.clip();ctx.drawImage(f.image,0,0);ctx.restore();}
function radius(index){const t=assets.config.slots[5].transforms[index],c=t.crop;return Math.max(...[[c.x,c.y],[c.x+c.w,c.y],[c.x,c.y+c.h],[c.x+c.w,c.y+c.h]].map(([x,y])=>Math.abs(transformPoint(x,y,t).x)))*p.monsterScale;}
const yOf=h=>(p.top+h*(p.bottom-p.top))*HEIGHT;
function render(){const t=clock.time;ctx.fillStyle=p.background;ctx.fillRect(0,0,WIDTH,HEIGHT);if(assets){const actor=actorAt(events,t,p,counts,fps);drawSprite(actor.slot,actor.frame,p.characterX*WIDTH,yOf(actor.height),p.characterScale);const choices=enabled();if(chart&&choices.length){const maxR=Math.max(...choices.map(v=>radius(v.index)),0);const travel=p.travelBeats*60/chart.meta.bpm;const leftDuration=Math.max(...choices.map(v=>{const r=radius(v.index);return(p.hitX*WIDTH+r)*travel/((1-p.hitX)*WIDTH+r);}),0);const first=Math.max(0,lastAt(events,t-leftDuration-.1,'time'));const last=lastAt(events,t+travel,'time');for(let i=first;i<=last;i++){const n=events[i],choice=choices[hash(chart.meta.seed??1,n.id)%choices.length],r=radius(choice.index),m=monsterAt(n,t,p,chart.meta.bpm,r);if(m.visible){drawSprite(5,choice.index,m.x,yOf(n.height),p.monsterScale);if(p.debug&&!recording){ctx.fillStyle='#263041';ctx.font='22px sans-serif';ctx.fillText(n.time.toFixed(3)+' s',m.x+15,yOf(n.height)-35);}}}if(p.mode==='hit'){const hitIndex=lastAt(events,t,'time');for(let i=hitIndex;i>=0&&t-events[i].time<counts[4]/fps;i--){const n=events[i];drawSprite(4,Math.floor((t-n.time)*fps),p.characterX*WIDTH+p.hitDx,yOf(n.height)+p.hitDy,p.fxScale);}}}if(p.debug&&!recording){ctx.strokeStyle='#df4764';ctx.lineWidth=2;ctx.beginPath();ctx.moveTo(p.hitX*WIDTH,0);ctx.lineTo(p.hitX*WIDTH,HEIGHT);ctx.moveTo(p.characterX*WIDTH-15,yOf(actor.height));ctx.lineTo(p.characterX*WIDTH+15,yOf(actor.height));ctx.moveTo(p.characterX*WIDTH,yOf(actor.height)-15);ctx.lineTo(p.characterX*WIDTH,yOf(actor.height)+15);ctx.stroke();ctx.strokeRect(p.characterX*WIDTH+p.hitDx-7,yOf(actor.height)+p.hitDy-7,14,14);ctx.fillStyle='#263041';ctx.font='24px sans-serif';ctx.fillText(`${t.toFixed(3)} s · seed ${chart?.meta.seed??1}`,30,40);}}$('#time').textContent=`${Math.max(0,t).toFixed(3)} / ${end().toFixed(3)} s`;$('#seek').value=Math.max(p.start,Math.min(end(),t));if(clock.playing&&t<p.start)$('#count').textContent=String(Math.ceil(p.start-t));else $('#count').textContent='';}
function validatePlay(){if(loading)throw Error('正在加载资源');if(!chart)throw Error('请先导入谱面');if(!clock.buffer)throw Error('请先导入音乐');if(!(end()>p.start&&end()<=clock.buffer.duration+.001))throw Error('片段时间必须在音乐范围内');const required=p.mode==='hit'?[0,1,2,3,4,5]:[0,5];if(required.some(i=>!assets?.frames[i]?.length||assets.frames[i].length!==assets.config.slots[i].files.length))throw Error('请在素材窗口载入并应用所需素材');if(!enabled().length)throw Error('至少启用一种怪物');if(chart.notes.some(n=>{const t=chart.meta.offsetSeconds+n.tick*60/(chart.meta.bpm*480);return t<0||t>clock.buffer.duration;}))throw Error('谱面含音乐范围以外的音符，请先在制谱器检查');if(p.mode==='hit'&&hitConflicts(events))throw Error('同刻多音符暂不支持全部击打，可切换全部 Miss');}
function tail(){if(!assets||!chart)return p.tail;let needed=p.tail;const n=events.at(-1);if(n){if(p.mode==='hit')needed=Math.max(needed,n.attackEnd-end(),n.move+p.moveDuration-end(),n.time+counts[4]/fps-end());else for(const c of enabled()){const r=radius(c.index),travel=p.travelBeats*60/chart.meta.bpm,speed=((1-p.hitX)*WIDTH+r)/travel;needed=Math.max(needed,n.time+(p.hitX*WIDTH+r)/speed-end());}}return Math.max(0,needed);}
async function play(restart=false,withCountdown=false){try{validatePlay();let from=restart?p.start:clock.time;if(from<p.start||from>=end())from=p.start;const pre=withCountdown?Math.max(p.countdown,p.travelBeats*60/chart.meta.bpm,p.moveLead,-p.attackOffset):0;await clock.play(from-pre,from,end(),end()+tail());if(!clock.playing)return;$('#play').textContent='暂停';status(recording?'录屏模式 · Esc 退出':'播放中');}catch(e){status(e.message,true);}}
$('#play').onclick=()=>clock.playing?pause():play();$('#restart').onclick=()=>play(true,true);$('#seek').oninput=e=>{clock.seek(Number(e.target.value));$('#play').textContent='播放';render();};
for(const el of document.querySelectorAll('[data-setting]'))el.onchange=()=>{pause();try{p=validateSettings({...p,[el.dataset.setting]:Number(el.value)});unsaved=true;rebuild();}catch(e){status(e.message,true);}syncUI();};
$('#mode').onchange=e=>{pause();p.mode=e.target.value;unsaved=true;rebuild();};$('#background').oninput=e=>{p.background=e.target.value;unsaved=true;render();};$('#debug').onchange=e=>{p.debug=e.target.checked;unsaved=true;render();};
function changeSeed(value){if(!chart){status('请先导入谱面',true);return;}if(!Number.isSafeInteger(value)||value<0||value>4294967295){status('Seed 必须是 0–4294967295 的整数',true);syncUI();return;}pause();chart.meta.seed=value;chartDirty=true;syncUI();render();status('Seed 已修改，请保存谱面');}
$('#seed').onchange=e=>changeSeed(Number(e.target.value));$('#random').onclick=()=>changeSeed(crypto.getRandomValues(new Uint32Array(1))[0]);
function download(name,value){const url=URL.createObjectURL(new Blob([typeof value==='string'?value:JSON.stringify(value,null,2)],{type:'application/json'}));const a=document.createElement('a');a.href=url;a.download=name;a.click();setTimeout(()=>URL.revokeObjectURL(url),1000);}
$('#exportChart').onclick=()=>{if(!chart)return status('请先导入谱面',true);download('chart.json',serializeChart(chart));chartDirty=false;status('已导出谱面，请确认下载文件已保存');};
function mismatch(c,m){const ref=c?.meta.music;return ref&&m&&(ref.name!==m.name||ref.size!==m.size||Math.abs(ref.duration-m.duration)>.1);}
$('#chart').onclick=()=>$('#chartFile').click();$('#music').onclick=()=>$('#musicFile').click();
$('#chartFile').onchange=async e=>{const f=e.target.files[0];if(!f||loading)return;try{const c=parseChart(await f.text());if(chartDirty&&!confirm('放弃尚未保存的谱面 seed 修改？'))return;if(mismatch(c,music)&&!confirm('音乐文件信息与谱面不同，仍然使用当前音乐？'))return;pause();chart=c;chartDirty=false;clock.seek(p.start);syncUI();rebuild();status(`已载入 ${c.notes.length} 个音符`);}catch(err){status(`谱面未载入：${err.message}`,true);}finally{e.target.value='';}};
$('#musicFile').onchange=async e=>{const f=e.target.files[0];if(!f||loading)return;loading=true;pause();status('正在解码音乐…');try{const b=await clock.decode(f);const m={name:f.name,size:f.size,duration:b.duration};if(mismatch(chart,m)&&!confirm('音乐文件信息与谱面不同，仍然使用这份音乐？'))return;clock.buffer=b;music=m;if(p.start>=b.duration)p.start=0;if(!p.end||p.end>b.duration||p.end<=p.start)p.end=b.duration;clock.seek(p.start);unsaved=true;syncUI();rebuild();status(`已载入音乐 · ${b.duration.toFixed(2)} 秒`);}catch(err){status(`音乐未载入：${err.message}`,true);}finally{loading=false;e.target.value='';}};
$('#materials').onclick=()=>{pause();$('#assetDialog').showModal();};
function closeAssets(){if(loading){status('素材正在加载，请稍候');return;}if(bridge()?.dirty&&!confirm('放弃素材窗口中尚未应用的修改？'))return;if(bridge()?.dirty)bridge().cancel();bridge()?.pause();$('#assetDialog').close();}
$('#closeAssets').onclick=closeAssets;$('#assetDialog').oncancel=e=>{e.preventDefault();closeAssets();};
$('#preset').onclick=async()=>{if(loading||!bridge())return;if(assets&&!confirm('使用项目原始素材替换当前素材配置？'))return;loading=true;$('#preset').disabled=true;status('正在载入项目素材…');try{for(let i=0;i<groups.length;i++){const entries=Object.entries(bundled).filter(([key])=>key.includes('/'+groups[i]+'/'));const files=await Promise.all(entries.map(async([key,url])=>new File([await (await fetch(url)).blob()],key.split('/').at(-1),{type:'image/png'})));await bridge().importGroup(i,files);}const cfg=bridge().getConfig();bridge().apply();const frames=bridge().applied.frames;const base=frames[0][0]?.bounds;for(let i=0;i<6;i++){cfg.slots[i].transforms=cfg.slots[i].transforms.map((_,j)=>{const f=frames[i][i===5?j:0];const t=assetDefaults(f.w,f.h);const b=i<4?base:f.bounds;if(b)t.anchor={x:b.x+b.w/2,y:b.y+b.h/2};return t;});}bridge().setConfig(cfg);bridge().apply();status('项目素材已载入，可在窗口中进一步校准锚点');}catch(err){status(`素材载入失败：${err.message}`,true);}finally{loading=false;$('#preset').disabled=false;}};
$('#save').onclick=()=>{download('renderer.json',{version:1,settings:p,assets:assets?.config??null});unsaved=false;status('已导出渲染配置；音乐、谱面和图片需单独保留');};
$('#open').onclick=()=>$('#configFile').click();$('#configFile').onchange=async e=>{const f=e.target.files[0];if(!f||loading)return;try{const c=JSON.parse(await f.text());if(c?.version!==1)throw Error('配置版本无效');const settings=validateSettings(c.settings);if(c.assets)parseConfig(JSON.stringify(c.assets));if((unsaved||bridge()?.dirty)&&!confirm('替换当前渲染配置及未应用的素材修改？'))return;if(!bridge())throw Error('素材窗口尚未准备好');pause();if(c.assets){bridge().setConfig(c.assets);bridge().apply();}else{bridge().setConfig({version:1,fps:8,slots:Array.from({length:6},()=>({files:[],transforms:[]}))});bridge().apply();}p=settings;unsaved=false;syncUI();clock.seek(p.start);rebuild();status('配置已载入；缺失素材请在素材窗口重新关联');}catch(err){status(`配置未载入：${err.message}`,true);}finally{e.target.value='';}};
$('#fullscreen').onclick=async()=>{try{await $('#screen').requestFullscreen();}catch(e){status('无法进入全屏：'+e.message,true);}};
$('#record').onclick=async()=>{try{validatePlay();await $('#screen').requestFullscreen();recording=true;$('#screen').classList.add('recording');await play(true,true);}catch(e){status(e.message,true);}};
window.addEventListener('keydown',e=>{if(e.code==='Space'&&!['INPUT','SELECT','TEXTAREA','BUTTON'].includes(document.activeElement.tagName)&&!$('#assetDialog').open){e.preventDefault();clock.playing?pause():play();}});
 document.addEventListener('fullscreenchange',()=>{if(!document.fullscreenElement){recording=false;$('#screen').classList.remove('recording');pause();render();}});
window.addEventListener('beforeunload',e=>{if(unsaved||chartDirty){e.preventDefault();e.returnValue='';}});
function loop(){if(clock.playing&&clock.time>=clock.until){pause();status('片段播放结束');}render();requestAnimationFrame(loop);}syncUI();rebuild();requestAnimationFrame(loop);
